'use client';

import { useState } from 'react';
import Link from 'next/link';
import styles from './page.module.css';
import TextPressure from './components/TextPressure';
import SmoothScroll from './components/SmoothScroll';
import HeroGeometric from '@/components/ui/hero-geometric';

export default function Home() {
  const clientUrl = typeof window !== 'undefined' 
    ? (process.env.NEXT_PUBLIC_CLIENT_URL || 'http://localhost:3001')
    : 'http://localhost:3001';

  // State for FAQ accordion
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  // State for persistent Chat Widget response
  const [chatResponse, setChatResponse] = useState<string | null>(null);
  const [chatInputLabel, setChatInputLabel] = useState<string | null>(null);

  // State for Hero Sandbox Simulator
  const [activeSandboxTab, setActiveSandboxTab] = useState<'code' | 'security' | 'presence'>('code');
  const [consoleLogs, setConsoleLogs] = useState<string[]>([
    "Ready to compile. Press 'Run Code' to execute secure sandbox."
  ]);
  const [isCompiling, setIsCompiling] = useState(false);

  const toggleFaq = (index: number) => {
    setOpenFaq(openFaq === index ? null : index);
  };

  const handleChatChoice = (choice: string, reply: string) => {
    setChatInputLabel(choice);
    setChatResponse(reply);
    setTimeout(() => {
      setChatResponse(null);
      setChatInputLabel(null);
    }, 6000);
  };

  const runSandboxCode = () => {
    if (isCompiling) return;
    setIsCompiling(true);
    setConsoleLogs(prev => [
      ...prev,
      ">> Initializing Judge0 compiler handshake...",
      ">> Provisioning isolated micro-container...",
      ">> Fetching workspace dependencies..."
    ]);

    setTimeout(() => {
      setConsoleLogs(prev => [
        ...prev,
        ">> Container active. Running script (main.py)...",
        ">> Integrity Check: Tab Loss Event: 0 detected",
        ">> Integrity Check: Clipboard monitor: SECURE",
        "Hello from DevMeet secure sandbox!",
        "Active collaborators: Siddharth, Jane",
        "Output complexity metrics: O(N log N)",
        ">> Test suite: 5 passed, 0 failed.",
        ">> Runtime: 0.12s | CPU: 1.4% | Memory: 8.2MB",
        ">> Process exited with code 0. Container de-allocated."
      ]);
      setIsCompiling(false);
    }, 1800);
  };

  const faqs = [
    {
      q: "How does DevMeet protect technical assessments from AI cheating?",
      a: "DevMeet monitors browser tab focus shifts and clipboard events. When a candidate attempts to copy large code blocks generated by external AI, the platform blocks the paste action, flags the event, and records a detailed log in the session timeline for review."
    },
    {
      q: "Is the sandboxed code execution environment secure?",
      a: "Absolutely. All compilers run inside secure, micro-virtualized Judge0/Piston containers. Candidates cannot access the host machine, file systems, or external networks, preventing malicious code runs during tests."
    },
    {
      q: "Can we review the candidate's exact coding process?",
      a: "Yes. DevMeet provides a playback timeline of the entire session. You can review the interview keystroke-by-keystroke, watch code execution attempts, check audio/video recordings, and view anti-cheat event markers."
    },
    {
      q: "How many collaborators can join a live coding room?",
      a: "Our standard rooms support up to 5 concurrent participants (ideal for pair programming and panel interviews), while enterprise collaborative channels support up to 50 active users with low-latency WebRTC streams."
    }
  ];

  return (
    <SmoothScroll>
      <>
        {/* Navigation Bar */}
        <nav className={styles.navBar}>
          <div className={styles.navLeft}>
            <span className={`${styles.logo} font-editorial`}>DevMeet</span>
          </div>
          <div className={styles.navLinks}>
            <a href="#features" className={`${styles.navLink} font-body`}>Features</a>
            <a href="#use-cases" className={`${styles.navLink} font-body`}>Use Cases</a>
            <Link href="/pricing" className={`${styles.navLink} font-body`}>Pricing</Link>
            <a href="#faq" className={`${styles.navLink} font-body`}>FAQs</a>
          </div>
          <div className={styles.navRight}>
            <a href={`${clientUrl}/login`} className={`${styles.loginLink} font-body`}>Log in</a>
            <a href={`${clientUrl}/signup`} className={`${styles.requestDemoBtn} font-tech`}>Request a demo</a>
          </div>
        </nav>

        <main className="relative">
          {/* Hero Section (2-Column Split) */}
          <section className={styles.heroSection}>
            {/* Background Shader: light canvas drift */}
            <div className="absolute inset-0 z-0 pointer-events-none">
              <HeroGeometric 
                color1="#f9f8f6" // Warm Cream
                color2="#eaebf8" // Lavender Mist
                speed={0.2}
                className="absolute inset-0 w-full h-full"
              />
            </div>

            {/* Left Column: Content */}
            <div className={`${styles.heroContent} relative z-10`}>
              <span className={styles.heroEyebrow}>Secure developer assessments</span>
              <h1 className={`${styles.heroHeadline} font-body`}>
                You can&apos;t evaluate builders if you&apos;re <em>not securing the workspace.</em>
              </h1>
              <p className={`${styles.heroSubheadline} font-body`}>
                DevMeet converges a collaborative Monaco editor, zero-lag calling, and sandboxed runtimes with advanced anti-cheat logging to make technical assessments authentic again.
              </p>
              <div className={styles.heroActions}>
                <a href={`${clientUrl}/dashboard`} className={`${styles.heroPrimaryBtn} font-tech`}>Try DevMeet for free</a>
                <a href="#features" className={`${styles.heroSecondaryBtn} font-tech`}>Explore features</a>
              </div>
            </div>

            {/* Right Column: Interactive Sandbox Simulator */}
            <div className="relative z-10 flex justify-center w-full">
              <div className={styles.sandboxCard}>
                <div className={styles.sandboxHeader}>
                  <div className={styles.sandboxWindowDots}>
                    <div className={styles.sandboxWindowDot} style={{ backgroundColor: '#ff5f56' }}></div>
                    <div className={styles.sandboxWindowDot} style={{ backgroundColor: '#ffbd2e' }}></div>
                    <div className={styles.sandboxWindowDot} style={{ backgroundColor: '#27c93f' }}></div>
                  </div>
                  <div className={styles.sandboxTabs}>
                    <button 
                      className={`${styles.sandboxTabBtn} ${activeSandboxTab === 'code' ? styles.sandboxTabBtnActive : ''}`}
                      onClick={() => setActiveSandboxTab('code')}
                    >
                      💻 Sandbox IDE
                    </button>
                    <button 
                      className={`${styles.sandboxTabBtn} ${activeSandboxTab === 'security' ? styles.sandboxTabBtnActive : ''}`}
                      onClick={() => setActiveSandboxTab('security')}
                    >
                      🛡️ Anti-Cheat
                    </button>
                    <button 
                      className={`${styles.sandboxTabBtn} ${activeSandboxTab === 'presence' ? styles.sandboxTabBtnActive : ''}`}
                      onClick={() => setActiveSandboxTab('presence')}
                    >
                      🎥 Live Session
                    </button>
                  </div>
                </div>

                <div className={styles.sandboxPanel}>
                  {activeSandboxTab === 'code' && (
                    <>
                      <div className={styles.sandboxEditor}>
                        <span style={{ color: '#ff79c6' }}>def</span> <span style={{ color: '#50fa7b' }}>quick_sort</span>(arr):<br />
                        &nbsp;&nbsp;&nbsp;&nbsp;<span style={{ color: '#ff79c6' }}>if</span> <span style={{ color: '#50fa7b' }}>len</span>(arr) &lt;= <span style={{ color: '#bd93f9' }}>1</span>: <span style={{ color: '#ff79c6' }}>return</span> arr<br />
                        &nbsp;&nbsp;&nbsp;&nbsp;pivot = arr[<span style={{ color: '#50fa7b' }}>len</span>(arr) // <span style={{ color: '#bd93f9' }}>2</span>]<br />
                        &nbsp;&nbsp;&nbsp;&nbsp;left = [x <span style={{ color: '#ff79c6' }}>for</span> x <span style={{ color: '#ff79c6' }}>in</span> arr <span style={{ color: '#ff79c6' }}>if</span> x &lt; pivot]<br />
                        &nbsp;&nbsp;&nbsp;&nbsp;mid = [x <span style={{ color: '#ff79c6' }}>for</span> x <span style={{ color: '#ff79c6' }}>in</span> arr <span style={{ color: '#ff79c6' }}>if</span> x == pivot]<br />
                        &nbsp;&nbsp;&nbsp;&nbsp;right = [x <span style={{ color: '#ff79c6' }}>for</span> x <span style={{ color: '#ff79c6' }}>in</span> arr <span style={{ color: '#ff79c6' }}>if</span> x &gt; pivot]<br />
                        &nbsp;&nbsp;&nbsp;&nbsp;<span style={{ color: '#ff79c6' }}>return</span> quick_sort(left) + mid + quick_sort(right)
                      </div>
                      <div className={styles.sandboxConsole}>
                        {consoleLogs.map((log, i) => (
                          <div key={i}>{log}</div>
                        ))}
                      </div>
                      <div className={styles.sandboxEditorFooter}>
                        <span style={{ color: '#888', fontSize: '0.7rem' }}>Runtime: Python 3.10</span>
                        <button 
                          className={`${styles.sandboxRunBtn} ${isCompiling ? styles.sandboxRunBtnDisabled : ''}`}
                          onClick={runSandboxCode}
                          disabled={isCompiling}
                        >
                          <span className="material-symbols-outlined" style={{ fontSize: '1rem' }}>
                            {isCompiling ? 'sync' : 'play_arrow'}
                          </span>
                          {isCompiling ? 'Running...' : 'Run Code'}
                        </button>
                      </div>
                    </>
                  )}

                  {activeSandboxTab === 'security' && (
                    <div className={styles.sandboxSecurity}>
                      <div className={styles.securityMetricGrid}>
                        <div className={styles.securityMetricCard}>
                          <span className={styles.securityMetricVal}>96%</span>
                          <span className={styles.securityMetricLabel}>Integrity Score</span>
                        </div>
                        <div className={styles.securityMetricCard}>
                          <span className={styles.securityMetricVal} style={{ color: '#ef4444' }}>1</span>
                          <span className={styles.securityMetricLabel}>Active Alerts</span>
                        </div>
                      </div>
                      <div>
                        <h4 className={styles.securityLogTitle}>Live Anti-Cheat Feed</h4>
                        <div className={styles.securityLogList}>
                          <div className={`${styles.securityLogItem} ${styles.securityLogItemAlert}`}>
                            <span className={styles.securityLogTime}>14:03:10</span>
                            <span className={styles.securityLogText}>
                              <strong>[BLOCKED]</strong> Copy-paste block: Paste of 145 lines matching GPT patterns rejected.
                            </span>
                          </div>
                          <div className={`${styles.securityLogItem} ${styles.securityLogItemAlert}`} style={{ borderLeftColor: '#f59e0b', backgroundColor: '#fffbeb' }}>
                            <span className={styles.securityLogTime}>14:02:45</span>
                            <span className={styles.securityLogText}>
                              <strong>[WARNING]</strong> Tab focus lost: Candidate switched window for 4.8 seconds.
                            </span>
                          </div>
                          <div className={`${styles.securityLogItem} ${styles.securityLogItemOk}`}>
                            <span className={styles.securityLogTime}>14:01:05</span>
                            <span className={styles.securityLogText}>
                              <strong>[SECURE]</strong> Keystroke dynamics analysis initialized.
                            </span>
                          </div>
                        </div>
                      </div>
                    </div>
                  )}

                  {activeSandboxTab === 'presence' && (
                    <div className={styles.sandboxPresence}>
                      <div className={styles.presenceRow}>
                        <div className={styles.presenceUser}>
                          <div className={styles.presenceAvatar}>SK</div>
                          <span className={styles.presenceName}>Siddharth (Candidate)</span>
                        </div>
                        <div className={styles.presenceMeta}>
                          <span className={styles.presenceLatency}>8ms</span>
                          <div className={styles.presenceMicWave}>
                            <div className={styles.presenceMicBar} style={{ animationDelay: '0.1s' }}></div>
                            <div className={styles.presenceMicBar} style={{ animationDelay: '0.3s' }}></div>
                            <div className={styles.presenceMicBar} style={{ animationDelay: '0.2s' }}></div>
                          </div>
                        </div>
                      </div>

                      <div className={styles.presenceRow}>
                        <div className={styles.presenceUser}>
                          <div className={styles.presenceAvatar} style={{ backgroundColor: 'var(--color-electric-cobalt)' }}>JW</div>
                          <span className={styles.presenceName}>Jane (Interviewer)</span>
                        </div>
                        <div className={styles.presenceMeta}>
                          <span className={styles.presenceLatency}>12ms</span>
                          <div className={styles.presenceMicWave}>
                            <div className={styles.presenceMicBar} style={{ animationDelay: '0.4s' }}></div>
                            <div className={styles.presenceMicBar} style={{ animationDelay: '0.1s' }}></div>
                            <div className={styles.presenceMicBar} style={{ animationDelay: '0.3s' }}></div>
                          </div>
                        </div>
                      </div>

                      <div className={styles.presenceRow}>
                        <div className={styles.presenceUser}>
                          <div className={styles.presenceAvatar} style={{ backgroundColor: '#10b981' }}>SC</div>
                          <span className={styles.presenceName}>Secure Compiler Daemon</span>
                        </div>
                        <div className={styles.presenceMeta}>
                          <span className={styles.presenceLatency} style={{ color: 'var(--color-electric-cobalt)', backgroundColor: 'var(--color-lavender-mist)' }}>Edge Sync</span>
                        </div>
                      </div>
                    </div>
                  )}
                </div>
              </div>
            </div>
          </section>

          {/* Logos Row */}
          <section className={styles.logosRow}>
            <p className={`${styles.logosTitle} font-tech uppercase`}>Evaluated by lead teams worldwide</p>
            <div className={styles.logosList}>
              <span className={styles.logoItem}>SLACK</span>
              <span className={styles.logoItem}>GITHUB</span>
              <span className={styles.logoItem}>LINEAR</span>
              <span className={styles.logoItem}>VERCEL</span>
              <span className={styles.logoItem}>HUBSPOT</span>
            </div>
          </section>

          {/* Step Cards Section */}
          <section id="use-cases" className={styles.stepSection}>
            <div className={styles.stepHeader}>
              <h2 className={`${styles.stepSectionTitle} font-body`}>
                Simple insight. Clear direction. <em>Active verification in 3 steps.</em>
              </h2>
              <p className={styles.stepSectionDesc}>
                DevMeet protects technical evaluations from start to finish, validating skills in secure assessments.
              </p>
            </div>
            <div className={styles.stepGrid}>
              {/* Card 1: Dark Navy */}
              <div className={`${styles.stepCard} ${styles.stepCardDark}`}>
                <div className={styles.stepTop}>
                  <span className={`${styles.stepBadge} ${styles.stepBadgeDark}`}>Step 1</span>
                  <h3 className={`${styles.stepCardTitle} font-body`}>Establish <em>integrity</em></h3>
                  <p className={styles.stepCardDesc}>
                    Deploy a secure coding sandbox instantly. Built-in out-of-tab monitoring and copy-paste limits flag anomalous activity as it happens.
                  </p>
                </div>
                <div className={styles.stepVisual}>
                  <span style={{ color: '#6272a4' }}># Active monitoring daemon</span><br />
                  integrity.log_focus_loss(<span style={{ color: '#50fa7b' }}>duration</span>=4.8)<br />
                  integrity.prevent_clipboard_paste(<span style={{ color: '#ff5555' }}>blocked</span>=True)
                </div>
              </div>

              {/* Card 2: Light Cream Border */}
              <div className={`${styles.stepCard} ${styles.stepCardLight}`}>
                <div className={styles.stepTop}>
                  <span className={`${styles.stepBadge} ${styles.stepBadgeLight}`}>Step 2</span>
                  <h3 className={`${styles.stepCardTitle} font-body`}>Observe <em>capability</em></h3>
                  <p className={styles.stepCardDesc}>
                    Watch coding capability in real-time. Live syntax syncing, WebRTC call channels, and micro-virtualized code compilation happen side-by-side.
                  </p>
                </div>
                <div className={styles.stepVisual}>
                  <div style={{ display: 'flex', gap: '4px', height: '36px', alignItems: 'flex-end', borderBottom: '1px solid #e0e0e0', paddingBottom: '4px' }}>
                    <div style={{ width: '8px', height: '18px', backgroundColor: '#2545ff' }}></div>
                    <div style={{ width: '8px', height: '24px', backgroundColor: '#0c1754' }}></div>
                    <div style={{ width: '8px', height: '14px', backgroundColor: '#2545ff' }}></div>
                    <div style={{ width: '8px', height: '32px', backgroundColor: '#2545ff' }}></div>
                  </div>
                  <div style={{ fontSize: '0.65rem', marginTop: '6px', color: '#666' }}>Execution latency: 8ms avg</div>
                </div>
              </div>

              {/* Card 3: Cobalt Border Accent */}
              <div className={`${styles.stepCard} ${styles.stepCardAccent}`}>
                <div className={styles.stepTop}>
                  <span className={`${styles.stepBadge} ${styles.stepBadgeAccent}`}>Step 3</span>
                  <h3 className={`${styles.stepCardTitle} font-body`}>Audit <em>authenticity</em></h3>
                  <p className={styles.stepCardDesc}>
                    Inspect the post-session audit trail. Step through coding timelines, check compilation outcomes, and audit recorded security warnings.
                  </p>
                </div>
                <div className={styles.stepVisual}>
                  <span style={{ color: '#0f6e61' }}>$ devmeet-audit verify</span><br />
                  <span style={{ color: '#2545ff' }}>&gt; Checking plagiarism profile...</span><br />
                  <span style={{ color: '#10b981' }}>&gt; Audit pass: No copy-paste match (0%)</span>
                </div>
              </div>
            </div>
          </section>

          {/* Feature Split Rows (Alternating Layouts) */}
          <section id="features" className={styles.featureSplitSection}>
            {/* Feature 1: Video Call */}
            <div className={styles.featureSplitRow}>
              <div className={styles.featureSplitContent}>
                <span className={styles.featureSplitKicker}>Assessment Engine</span>
                <h2 className={`${styles.featureSplitHeading} font-body`}>
                  Multiplayer Monaco workspace with <em>zero-lag video</em>
                </h2>
                <p className={styles.featureSplitBody}>
                  Conduct remote interviews in a fully unified, live IDE panel. See, hear, and code alongside candidates with sub-10ms editing latency and crystal clear voice streams.
                </p>
                <ul className={styles.featureSplitList}>
                  <li className={styles.featureSplitListItem}>
                    <span className="material-symbols-outlined" style={{ color: 'var(--color-electric-cobalt)' }}>check_circle</span>
                    <span className="font-body">Embedded WebRTC peer calling with custom participant sidebar</span>
                  </li>
                  <li className={styles.featureSplitListItem}>
                    <span className="material-symbols-outlined" style={{ color: 'var(--color-electric-cobalt)' }}>check_circle</span>
                    <span className="font-body">Full Monaco editor workspace with tab navigation and file explorer</span>
                  </li>
                  <li className={styles.featureSplitListItem}>
                    <span className="material-symbols-outlined" style={{ color: 'var(--color-electric-cobalt)' }}>check_circle</span>
                    <span className="font-body">P2P sync engine built for zero conflicts during concurrent edits</span>
                  </li>
                </ul>
              </div>
              <div className={styles.featureSplitVisual}>
                <div className={styles.mockupContainer}>
                  <div className={styles.videoGrid}>
                    <div className={styles.videoTile}>
                      <div className={styles.videoAvatar}>SK</div>
                      <span className={styles.videoBadge}>Siddharth (Candidate)</span>
                    </div>
                    <div className={styles.videoTile}>
                      <div className={styles.videoAvatar} style={{ backgroundColor: 'var(--color-electric-cobalt)' }}>AH</div>
                      <span className={styles.videoBadge}>Alex (Interviewer)</span>
                    </div>
                    <div className={styles.videoTile}>
                      <div className={styles.videoAvatar} style={{ backgroundColor: '#10b981' }}>JW</div>
                      <span className={styles.videoBadge}>Jane (Lead Developer)</span>
                    </div>
                    <div className={styles.videoTile}>
                      <div className={styles.videoAvatar} style={{ backgroundColor: '#f59e0b' }}>MT</div>
                      <span className={styles.videoBadge}>Sys Daemon (Edge host)</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Feature 2: Monaco Editor (Reverse Column) */}
            <div className={styles.featureSplitRow} style={{ direction: 'rtl' }}>
              <div className={styles.featureSplitContent} style={{ direction: 'ltr' }}>
                <span className={styles.featureSplitKicker}>Anti-Cheating Suite</span>
                <h2 className={`${styles.featureSplitHeading} font-body`}>
                  AI plagiarism control &amp; <em>tab-switch detection</em>
                </h2>
                <p className={styles.featureSplitBody}>
                  Defend test integrity from GPT copy-pasting. Detect out-of-tab window focus loss, block clipboard insertions of external AI answers, and run passive integrity evaluations.
                </p>
                <ul className={styles.featureSplitList}>
                  <li className={styles.featureSplitListItem}>
                    <span className="material-symbols-outlined" style={{ color: 'var(--color-electric-cobalt)' }}>check_circle</span>
                    <span className="font-body">Out-of-tab duration tracking and loss of window focus alerts</span>
                  </li>
                  <li className={styles.featureSplitListItem}>
                    <span className="material-symbols-outlined" style={{ color: 'var(--color-electric-cobalt)' }}>check_circle</span>
                    <span className="font-body">Clipboard injection prevention blocks pasting of external code templates</span>
                  </li>
                  <li className={styles.featureSplitListItem}>
                    <span className="material-symbols-outlined" style={{ color: 'var(--color-electric-cobalt)' }}>check_circle</span>
                    <span className="font-body">Keystroke structure dynamics flag anomalous speed writing spikes</span>
                  </li>
                </ul>
              </div>
              <div className={styles.featureSplitVisual} style={{ direction: 'ltr' }}>
                <div className={styles.mockupContainer}>
                  <div className={styles.editorHeader}>
                    <div className={styles.dots}>
                      <div className={styles.dot} style={{ backgroundColor: '#ff5f56' }}></div>
                      <div className={styles.dot} style={{ backgroundColor: '#ffbd2e' }}></div>
                      <div className={styles.dot} style={{ backgroundColor: '#27c93f' }}></div>
                    </div>
                    <div className={styles.editorTabs}>
                      <div className={`${styles.editorTab} ${styles.editorTabActive}`}>assessment_anti_cheat.py</div>
                    </div>
                  </div>
                  <div className={styles.editorContent} style={{ backgroundColor: '#1e1b1e', color: '#ff79c6' }}>
                    <span style={{ color: '#6272a4' }}># Monitoring active interview integrity</span><br />
                    <span style={{ color: '#ff79c6' }}>if</span> candidate.switched_tabs():<br />
                    &nbsp;&nbsp;&nbsp;&nbsp;session.log_integrity_warning(<span style={{ color: '#f1fa8c' }}>&quot;Tab Focus Lost&quot;</span>)<br />
                    <br />
                    <span style={{ color: '#ff79c6' }}>if</span> candidate.attempted_paste() &gt; <span style={{ color: '#bd93f9' }}>100</span>:<br />
                    &nbsp;&nbsp;&nbsp;&nbsp;clipboard.block_paste()<br />
                    &nbsp;&nbsp;&nbsp;&nbsp;session.flag_security_risk(<span style={{ color: '#f1fa8c' }}>&quot;AI Paste Attempt Blocked&quot;</span>)<span className={styles.editorCursor}></span>
                  </div>
                </div>
              </div>
            </div>

            {/* Feature 3: Sandboxed Compiler */}
            <div className={styles.featureSplitRow}>
              <div className={styles.featureSplitContent}>
                <span className={styles.featureSplitKicker}>Sandboxed Runtimes</span>
                <h2 className={`${styles.featureSplitHeading} font-body`}>
                  Isolated micro-containers for <em>safe code execution</em>
                </h2>
                <p className={styles.featureSplitBody}>
                  Compile and run code instantly in isolated virtual environments. Sandbox micro-containers (Judge0/Piston) isolate execution from external networks and secure the workspace.
                </p>
                <ul className={styles.featureSplitList}>
                  <li className={styles.featureSplitListItem}>
                    <span className="material-symbols-outlined" style={{ color: 'var(--color-electric-cobalt)' }}>check_circle</span>
                    <span className="font-body">Micro-virtualized sandboxes isolate candidate code runs entirely</span>
                  </li>
                  <li className={styles.featureSplitListItem}>
                    <span className="material-symbols-outlined" style={{ color: 'var(--color-electric-cobalt)' }}>check_circle</span>
                    <span className="font-body">Real-time compilation and execution logs stream directly to all users</span>
                  </li>
                  <li className={styles.featureSplitListItem}>
                    <span className="material-symbols-outlined" style={{ color: 'var(--color-electric-cobalt)' }}>check_circle</span>
                    <span className="font-body">Pre-configured environments for Python, Node.js, Rust, Go, C++, etc.</span>
                  </li>
                </ul>
              </div>
              <div className={styles.featureSplitVisual}>
                <div className={styles.mockupContainer}>
                  <div className={styles.compilerMockup}>
                    <div className={styles.compilerHeader}>
                      <span>Secure Compiler Environment</span>
                      <span>Execution daemon (status: secure)</span>
                    </div>
                    <div className={styles.compilerConsole}>
                      $ python quick_sort.py --verify<br />
                      <span style={{ color: '#fff' }}>&gt; Container instance: running...</span><br />
                      <span style={{ color: '#fff' }}>&gt; Network access: disabled (sandbox)</span><br />
                      <br />
                      Validating quick sort correctness...<br />
                      Test 1: Unsorted integer array: PASSED.<br />
                      Test 2: Empty input safety check: PASSED.<br />
                      Test 3: Reverse sorted edge cases: PASSED.<br />
                      <br />
                      All test assertions verified successfully. Exit code: 0.<br />
                      <span className={styles.compilerInput}>$ deallocating execution container... [OK]</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* Pastel Badges / Equip Managers Row */}
          <section className={styles.equipSection}>
            <div className={styles.equipHeader}>
              <span className="font-tech uppercase" style={{ color: 'var(--color-secondary)', fontSize: '0.75rem', letterSpacing: '0.12em', display: 'block', marginBottom: '1.25rem' }}>Management &amp; Culture</span>
              <h2 className={`${styles.stepSectionTitle} font-body`}>
                To actions on <em>engineering collaboration</em>
              </h2>
            </div>
            <div className={styles.equipGrid}>
              <div className={`${styles.equipCard} ${styles.equipCardPurple}`}>
                <span className={styles.equipCardBadge}>To align</span>
                <h3 className={`${styles.equipTitle} font-body`}>Keep team members <em>focused</em></h3>
                <p className={styles.equipCopy}>
                  Create dedicated, persistent workspace rooms for active sprints or project modules.
                </p>
              </div>
              <div className={`${styles.equipCard} ${styles.equipCardCyan}`}>
                <span className={styles.equipCardBadge}>To grow</span>
                <h3 className={`${styles.equipTitle} font-body`}>Map out <em>developer paths</em></h3>
                <p className={styles.equipCopy}>
                  Standardize technical assessment templates to build reliable interviewing pipelines.
                </p>
              </div>
              <div className={`${styles.equipCard} ${styles.equipCardOrange}`}>
                <span className={styles.equipCardBadge}>To track</span>
                <h3 className={`${styles.equipTitle} font-body`}>Run <em>daily checkins</em></h3>
                <p className={styles.equipCopy}>
                  Execute daily standups with collaborative terminals to review code modifications in real time.
                </p>
              </div>
              <div className={`${styles.equipCard} ${styles.equipCardPink}`}>
                <span className={styles.equipCardBadge}>To retain</span>
                <h3 className={`${styles.equipTitle} font-body`}>Spot <em>review blockages</em></h3>
                <p className={styles.equipCopy}>
                  Identify pull request latency and code bottlenecks early to keep developer velocity high.
                </p>
              </div>
            </div>
          </section>

          {/* Call to Action Banner */}
          <section className={styles.ctaSection}>
            <div className={styles.ctaBanner}>
              <h2 className={`${styles.ctaHeadline} font-body`}>
                Evaluate with confidence. Collaborate with <em>absolute security.</em>
              </h2>
              <p className={styles.ctaSubheadline}>
                Join 50,000+ developers building and testing on the ultimate collaborative platform.
              </p>
              <a href={`${clientUrl}/signup`} className={`${styles.ctaPillBtn} font-tech`}>Start a Session for free</a>
            </div>
          </section>

          {/* Resources / Blog Section */}
          <section className={styles.resourcesSection}>
            <div className={styles.resourcesHeader}>
              <h2 className={`${styles.resourcesTitle} font-body`}>Read about <em>technical evaluation</em></h2>
              <a href="#" className={styles.viewAllLink}>
                <span>View all articles</span>
                <span className="material-symbols-outlined">arrow_right_alt</span>
              </a>
            </div>
            <div className={styles.resourcesGrid}>
              {/* Blog Post 1 */}
              <div className={styles.resourceCard}>
                <div className={styles.resourceImgContainer}>
                  <svg width="100%" height="100%" viewBox="0 0 100 100" preserveAspectRatio="none">
                    <defs>
                      <linearGradient id="g1" x1="0%" y1="0%" x2="100%" y2="100%">
                        <stop offset="0%" stopColor="#e3e4ff" />
                        <stop offset="100%" stopColor="#2545ff" />
                      </linearGradient>
                    </defs>
                    <rect width="100" height="100" fill="url(#g1)" />
                    <circle cx="50" cy="50" r="20" fill="rgba(255,255,255,0.15)" />
                  </svg>
                </div>
                <div className={styles.resourceMeta}>
                  <span className={styles.resourceMetaCategory}>Security</span>
                  <span>•</span>
                  <span>5 min read</span>
                </div>
                <h3 className={styles.resourceCardTitle}>How collaborative IDEs are reshaping technical assessments</h3>
              </div>

              {/* Blog Post 2 */}
              <div className={styles.resourceCard}>
                <div className={styles.resourceImgContainer}>
                  <svg width="100%" height="100%" viewBox="0 0 100 100" preserveAspectRatio="none">
                    <defs>
                      <linearGradient id="g2" x1="0%" y1="0%" x2="100%" y2="100%">
                        <stop offset="0%" stopColor="#e0f7f4" />
                        <stop offset="100%" stopColor="#0c1754" />
                      </linearGradient>
                    </defs>
                    <rect width="100" height="100" fill="url(#g2)" />
                    <rect x="30" y="30" width="40" height="40" fill="rgba(255,255,255,0.1)" transform="rotate(45 50 50)" />
                  </svg>
                </div>
                <div className={styles.resourceMeta}>
                  <span className={styles.resourceMetaCategory}>Integrity</span>
                  <span>•</span>
                  <span>8 min read</span>
                </div>
                <h3 className={styles.resourceCardTitle}>Designing low-latency workspaces for remote engineering teams</h3>
              </div>

              {/* Blog Post 3 */}
              <div className={styles.resourceCard}>
                <div className={styles.resourceImgContainer}>
                  <svg width="100%" height="100%" viewBox="0 0 100 100" preserveAspectRatio="none">
                    <defs>
                      <linearGradient id="g3" x1="0%" y1="0%" x2="100%" y2="100%">
                        <stop offset="0%" stopColor="#fde2eb" />
                        <stop offset="100%" stopColor="#2545ff" />
                      </linearGradient>
                    </defs>
                    <rect width="100" height="100" fill="url(#g3)" />
                    <path d="M20,80 L50,20 L80,80 Z" fill="rgba(255,255,255,0.15)" />
                  </svg>
                </div>
                <div className={styles.resourceMeta}>
                  <span className={styles.resourceMetaCategory}>Evaluations</span>
                  <span>•</span>
                  <span>4 min read</span>
                </div>
                <h3 className={styles.resourceCardTitle}>Why context switching is the silent killer of developer focus</h3>
              </div>
            </div>
          </section>

          {/* FAQ Accordion Section */}
          <section id="faq" className={styles.faqSection}>
            <div className={styles.faqLeft}>
              <div className={styles.faqLeftSticky}>
                <h2 className={`${styles.faqTitle} font-body`}>
                  Answering your questions in less about <em>30 seconds.</em>
                </h2>
              </div>
            </div>
            <div className={styles.faqRight}>
              {faqs.map((faq, index) => {
                const isOpen = openFaq === index;
                return (
                  <div key={index} className={styles.faqItem}>
                    <button className={`${styles.faqQuestion} font-body`} onClick={() => toggleFaq(index)}>
                      <span>{faq.q}</span>
                      <span className={`material-symbols-outlined ${styles.faqChevron} ${isOpen ? styles.faqChevronActive : ''}`}>
                        expand_more
                      </span>
                    </button>
                    <div className={styles.faqAnswer} style={{ maxHeight: isOpen ? '250px' : '0px' }}>
                      <div className={styles.faqAnswerInner}>
                        <p>{faq.a}</p>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </section>
        </main>

        {/* Persistent Chat Widget */}
        <div className={styles.chatWidget}>
          <div className={styles.chatMain}>
            <div className={styles.chatAvatar}>DM</div>
            <div className={styles.chatBody}>
              <span className={styles.chatSender}>DevMeet Assistant</span>
              <p className={styles.chatMessage}>
                {chatResponse ? (
                  <span>
                    <strong>Your choice:</strong> {chatResponse}
                  </span>
                ) : (
                  "Want to see DevMeet's security and compilers in action? Ask us anything!"
                )}
              </p>
            </div>
          </div>
          <div className={styles.chatChoices}>
            <button 
              className={styles.chatChip} 
              onClick={() => handleChatChoice("Anti-Cheat Details", "We log clipboard copy attempts and monitor out-of-tab durations to ensure authentic coding during tech tests.")}
            >
              Anti-Cheat
            </button>
            <button 
              className={styles.chatChip} 
              onClick={() => handleChatChoice("Compiler Security", "All runs compile in isolated Judge0 containers, blocking network/system compromises during sessions.")}
            >
              Compiler
            </button>
            <button 
              className={styles.chatChip} 
              onClick={() => handleChatChoice("Pricing", "DevMeet is free for open source and single interviewers, with team plans starting at $15/user.")}
            >
              Pricing
            </button>
          </div>
        </div>

        {/* Premium Footer */}
        <footer className={styles.premiumFooter}>
          <div className={styles.footerInner}>
            <div className={styles.footerLeft}>
              <div className={styles.footerBrand}>
                <span className={`${styles.footerLogo} font-editorial`}>DevMeet</span>
                <p className={styles.footerCopyright}>
                  © 2026 DevMeet. Engineered for secure assessments and peer collaboration.
                </p>
              </div>
              <div className={styles.footerLinksGrid}>
                <div className={styles.footerLinksGroup}>
                  <h4>Platform</h4>
                  <a href="#">Assessment Docs</a>
                  <a href="#">API Reference</a>
                  <a href="#">Compiler Runtimes</a>
                </div>
                <div className={styles.footerLinksGroup}>
                  <h4>Trust &amp; Security</h4>
                  <a href="#">Integrity Audit</a>
                  <a href="#">Terms of Service</a>
                  <a href="#">Security compliance</a>
                </div>
                <div className={styles.footerLinksGroup}>
                  <h4>Company</h4>
                  <a href="#">About Us</a>
                  <a href="#">Blog</a>
                  <a href="#">Case Studies</a>
                </div>
              </div>
            </div>
            <div className={styles.footerRight}>
              <TextPressure
                text="CONNECT"
                flex={true}
                scale={false}
                textColor="rgba(255, 255, 255, 0.05)"
                minFontSize={200}
              />
            </div>
          </div>
        </footer>
      </>
    </SmoothScroll>
  );
}
